### ISSUE TITLE
Implement API Key Management and Configuration for Fire Circle

### ISSUE THREAD

**Issue by fsgeek** [fsgeek/Mallku#26]
## Description
The Fire Circle needs a secure and flexible system for managing API keys and configuration for multiple AI model providers. This should support both development and production environments while maintaining security best practices.

## Current State
- Basic secrets management exists in `src/mallku/core/secrets.py`
- Configuration framework in `src/mallku/core/config.py`
- No specific handling for multiple AI provider credentials

### 1. Secure Key Storage
- Encrypted storage for API keys
- Support for environment variables
- Integration with Docker secrets for containerized deployments
- Key rotation capabilities

### 2. Provider Configuration
- Per-provider configuration schemas
- Model selection preferences
- Rate limiting configurations
- Cost tracking thresholds
- Fallback provider chains

### 3. Development Support
- Easy setup for local development
- Test key management
- Mock provider support
- Clear error messages for missing configuration

### 4. Multi-Environment Support
- Development, staging, and production configurations
- Environment-specific provider selections
- Budget limits per environment
- Audit logging for key usage

### Configuration Structure
```yaml
fire_circle:
  providers:
    anthropic:
      api_key: ${ANTHROPIC_API_KEY}
      models:
        - claude-3-opus
        - claude-3-sonnet
      rate_limit: 100/min
      monthly_budget: 500
    google:
      api_key: ${GOOGLE_AI_KEY}
      models:
        - gemini-pro
        - gemini-ultra
      rate_limit: 60/min
    mistral:
      api_key: ${MISTRAL_API_KEY}
      models:
        - mistral-large
        - mixtral-8x7b
    local:
      ollama:
        endpoint: http://localhost:11434
        models:
          - llama2
          - mistral
```

### Security Requirements
- No hardcoded keys in source code
- Keys never logged or exposed in errors
- Secure transmission to model adapters
- Access control for key management operations

## Acceptance Criteria
- [ ] Configuration schema defined and validated
- [ ] Secure key storage implementation
- [ ] Environment variable support
- [ ] Docker secrets integration
- [ ] Key rotation mechanism
- [ ] Configuration validation on startup
- [ ] Clear documentation for setup
- [ ] Unit tests for configuration loading
- [ ] Security audit passed

## Related Work
- Depends on Issue #25 (AI Model Adapters)
- Integrates with existing security architecture
- Extends core configuration system
